version: '3.4'

networks:
  frontend:
  backend:

secrets:
  mysql_root_password:
     file: .secrets/mysql_root_password
  mysql_user:
     file: .secrets/mysql_user
  mysql_password:
     file: .secrets/mysql_password

services:
  nginx:
    image: nginx:1.25
    volumes:
        - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
        - "./.sslc9ekey/bundle.crt:/etc/ssl/certs/server.crt:ro"
        - "./.sslc9ekey/IYTEJOKERSSLSertifika.key:/etc/ssl/certs/server.key:ro" 
        - "./.sslc9ekey/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro"
        - "/dockerfiles/volumes/wordpress-code/:/var/www/html:rw"
        - "/dockerfiles/volumes/wordpress-content/:/var/www/html/wp-content:rw"
        - "/dockerfiles/volumes/wordpress-uploads/:/var/www/html/wp-content/uploads:rw"
    ports:
        - "80:80"
        - "443:443"
    networks:
        - frontend
    depends_on:
        - wordpress
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  wordpress:
    image: wordpress:6.4-php8.1-fpm
    volumes: 
        - "./config/php/php.ini:/usr/local/etc/php/php.ini:ro"
        - "/dockerfiles/volumes/wordpress-code/:/var/www/html:rw"
        - "/dockerfiles/volumes/wordpress-content/:/var/www/html/wp-content:rw" 
        - "/dockerfiles/volumes/wordpress-uploads/:/var/www/html/wp-content/uploads:rw"
    secrets:
        - mysql_user
        - mysql_password
    environment:
        - WORDPRESS_DB_NAME=wpdbs
        - WORDPRESS_TABLE_PREFIX=wp_
        - WORDPRESS_DB_HOST=database
        - WORDPRESS_DB_USER_FILE=/run/secrets/mysql_user
        - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/mysql_password
    networks:
        - frontend
        - backend
    depends_on:
        - database
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  database:
    image: mariadb:11.2
    volumes:
        - "/dockerfiles/volumes/mariadb-data/:/var/lib/mysql:rw"
    secrets:
        - mysql_root_password
        - mysql_user
        - mysql_password
    environment:
        - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
        - MYSQL_USER_FILE=/run/secrets/mysql_user
        - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
    networks:
        - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9060:80
    networks:
      - backend
    depends_on:
      - database
    environment:
        - PMA_ARBITRARY=1
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
